### ISSUE TITLE
Incorrect description and youtube link

### ISSUE THREAD

**Issue by bharathr0209** [openshift-cs/rosaworkshop#18]
While the description in READ ME says 'Deploying our first app on a ROSA cluster' and links to 'https://youtu.be/KbzUbXWs6Ck', this isn't really about application deployment on ROSA. It is instead showing how to enable ROSA and set it up on AWS.

The description is poorly written with no steps elaborating how this repo can be used for a sample app deployment via S2I. May be explanation is missing

**Comment by 0kashi** [comment]
Thanks for the input and sorry for the delayed response. The description has since been updated.  Also, if you want the process for using that repo with s2i you can follow the process here: https://www.rosaworkshop.io/ostoy/10-deployment_s2i/
