### ISSUE TITLE
Autoscaling fails as default machine pool name is "Default"

### ISSUE THREAD

**Issue by mayurshetty** [openshift-cs/rosaworkshop#6]
Under "Setting up cluster autoscaling"
2. Now run the following to add autoscaling to that machine pool.

The below command fails as the machine pool name is Default
For example:
$ rosa edit machinepool -c my-rosa-cluster --enable-autoscaling default --min-replicas=2 --max-replicas=4

**Screen-shot:**
mshetty@mshetty-mac ROSA % rosa edit machinepool --replicas=4 --cluster=my-rosa-cluster db-nodes-mp
mshetty@mshetty-mac ROSA % rosa edit machinepool -c my-rosa-cluster --enable-autoscaling default --min-replicas=2 --max-replicas=4
E: Failed to get machine pool 'default' for cluster 'my-rosa-cluster'
mshetty@mshetty-mac ROSA % rosa edit machinepool -c my-rosa-cluster --enable-autoscaling Default --min-replicas=2 --max-replicas=4
mshetty@mshetty-mac ROSA % rosa list machinepool --cluster=my-rosa-cluster
ID               AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS                  TAINTS    AVAILABILITY ZONES
Default          Yes          2-4       m5.xlarge                                        us-west-2a
large-node-pool  No           3         m5.2xlarge     app=db, tier=backend              us-west-2a
db-nodes-mp      No           4         m5.xlarge      app=db, tier=backend              us-west-2a
mshetty@mshetty-mac ROSA %

**Comment by 0kashi** [comment]
corrected.
