### ISSUE TITLE
Add a screenshot to the Health Check section 

### ISSUE THREAD

**Issue by mayurshetty** [openshift-cs/rosaworkshop#7]
OpenShift internal Lab -> Health Check -> Intentionally crash the pod

Add a screenshot similar to this as it's not clear that we switching from the OpenShift console to the App.

![Screen Shot 2021-04-13 at 9 16 43 PM](https://user-images.githubusercontent.com/5749874/114654052-2d144100-9c9e-11eb-8562-bc1a0a0df9d9.png)
### ###

**Comment by 0kashi** [comment]
completed.
