### ISSUE TITLE
Delete the cluster

### ISSUE THREAD

**Issue by mayurshetty** [openshift-cs/rosaworkshop#8]
mshetty@mshetty-mac ROSA % rosa list clusters                                                                               
ID                                NAME             STATE
1k1ofojltll20n9rsr8moh495c6uohfv  my-rosa-cluster  ready

Deleting the cluster as follows fails:
mshetty@mshetty-mac ROSA % rosa delete cluster my-rosa-cluster
Error: required flag(s) "cluster" not set
Usage:
  rosa delete cluster [flags]

Examples:
  Delete a cluster named "mycluster"
  rosa delete cluster mycluster

  Delete a cluster using the --cluster flag
  rosa delete cluster --cluster=mycluster

Flags:
  -c, --cluster string   Name or ID of the cluster to delete.
  -h, --help             help for cluster
      --region string    Use a specific AWS region, overriding the AWS_REGION environment variable.
      --watch            Watch cluster uninstallation logs.

Global Flags:
      --debug            Enable debug mode.
      --profile string   Use a specific AWS profile from your credential file.
  -y, --yes              Automatically answer yes to confirm operation.

Failed to execute root command: required flag(s) "cluster" not set

mshetty@mshetty-mac ROSA % 

**Fix: Need to use the --cluster** 

mshetty@mshetty-mac ROSA % rosa delete cluster --cluster=my-rosa-cluster 
? Are you sure you want to delete cluster my-rosa-cluster? (y/N)

**Comment by 0kashi** [comment]
Corrected.
